services:
  api:
    build: .
    working_dir: /app/api
    volumes:
      - ./:/app
    ports:
      - "8080:8080"
    command: [ "lapis", "server" ]
  db:
    image: postgres:15.4
    restart: always
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: rinhadebackend
      POSTGRES_PASSWORD: rinhadebackend
      POSTGRES_DB: rinhadebackend
