services:
  api1: &api
    sysctls:
      net.core.somaxconn: 4096
    container_name: api1
    build: .
    working_dir: /app/api
    volumes:
      - ./:/app
    ports:
      - "80"
    depends_on:
      db:
        condition: service_healthy
    command: [ "lapis", "server" ]
    environment:
      - LAPIS_ENVIRONMENT=${API_ENVIRONMENT:-development}
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '512MB'
    networks:
      - rinhadebackend
    healthcheck:
      test: curl -o /dev/null -s --retry 0 --head http://localhost:80/contagem-pessoas || exit 1
      interval: 15s
      timeout: 5s
      retries: 10
      start_period: 10s
  api2:
    <<: *api
    container_name: api2

  lb:
    sysctls:
      net.core.somaxconn: 4096
    container_name: lb
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      api1:
        condition: service_healthy
      api2:
        condition: service_healthy
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '128MB'
    networks:
      - rinhadebackend

  db:
    container_name: db
    image: postgres:15.4
    restart: always
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: rinhadebackend
      POSTGRES_PASSWORD: rinhadebackend
      POSTGRES_DB: rinhadebackend
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '1GB'
    command:
      [
        "postgres",
        "-c",
        "config_file=/etc/postgresql/postgresql.conf"
      ]
    networks:
      - rinhadebackend
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U rinhadebackend" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s

  pgbouncer:
    container_name: pgbouncer
    image: bitnami/pgbouncer:latest
    ports:
      - "6432:6432"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./pgbouncer.ini:/bitnami/pgbouncer/conf/pgbouncer.ini
      - ./userlist.txt:/etc/pgbouncer/userlist.txt
    environment:
      - PGBOUNCER_DATABASES=*:host=db port=5432
      - POSTGRESQL_HOST=db
      - POSTGRESQL_PASSWORD=rinhadebackend
      - PGBOUNCER_LISTEN_PORT=6432
      - PGBOUNCER_LISTEN_ADDR=*
      - PGBOUNCER_ADMIN_USERS=admin
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: '920MB'
    networks:
      - rinhadebackend

networks:
  rinhadebackend:
