@apiURL = http://localhost:8080
@jsonContentType = application/json

###

POST {{apiURL}}/pessoas
Content-Type: {{jsonContentType}}

{
    "apelido": "josé",
    "nome": "José Roberto",
    "nascimento": "2000-10-01",
    "stack": ["C#", "Node", "Oracle"]
}

###

GET {{apiURL}}/pessoas/b3f209da-7d62-4903-b0a7-a50aefdd01d5
