@apiURL = http://localhost:9999
@jsonContentType = application/json

###

POST {{apiURL}}/pessoas
Content-Type: {{jsonContentType}}

{
    "apelido": "josé{{$randomInt 1 1000}}{{$timestamp}}",
    "nome": "José Roberto",
    "nascimento": "2000-10-01",
    "stack": ["C#", "Node", "Oracle"]
}

###
# @prompt id
GET {{apiURL}}/pessoas/{{id}}


###

GET {{apiURL}}/contagem-pessoas

### Valid request while using term search

# @prompt term
GET {{apiURL}}/pessoas?t={{term}}

### Invalid request while using term search

GET {{apiURL}}/pessoas?t=
