@apiURL = http://localhost:8080
@jsonContentType = application/json

###

POST {{apiURL}}
Content-Type: {{jsonContentType}}

{
    "apelido": "josé",
    "nome": "José Roberto",
    "nascimento": "2000-10-01",
    "stack": ["C#", "Node", "Oracle"]
}
