CREATE TEXT SEARCH CONFIGURATION TERM_SEARCH (COPY = portuguese);
ALTER TEXT SEARCH CONFIGURATION TERM_SEARCH
    ALTER MAPPING FOR hword, hword_part, word WITH portuguese_stem;

CREATE TABLE IF NOT EXISTS pessoas (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    apelido VARCHAR(32) UNIQUE NOT NULL,
    nome VARCHAR(100) NOT NULL,
    nascimento DATE NOT NULL,
    stack VARCHAR(1024),
    TERM_SEARCH TSVECTOR GENERATED ALWAYS AS (
        TO_TSVECTOR('TERM_SEARCH', nome || ' ' || apelido || ' ' || stack)
    ) STORED
);

CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_pessoas_term_search ON PESSOAS USING GIN (TERM_SEARCH);
